const ActionTypes = {
  FETCH_DATA: 'FETCH_DATA',
  FETCH_DATA_ERROR: 'FETCH_DATA_ERROR',
  FETCH_DATA_LOADING: 'FETCH_DATA_LOADING',
  FETCH_LOCAL_DATA: 'FETCH_LOCAL_DATA',
  FETCH_LOCAL_DATA_ERROR: 'FETCH_LOCAL_DATA_ERROR',
  FETCH_LOCAL_DATA_LAODING: 'FETCH_LOCAL_DATA_LAODING',
  JOIN_MISSION: 'JOIN_MISSION',
  LEAVE_MISSION: 'LEAVE_MISSION',
  STORAGE_DATA: 'STORAGE_DATA',
};
export default ActionTypes;
